{% set name = "wil" %}
{% set version = "1.0.250325.1" %}
{% set sha256 = "c9e667d5f86ded43d17b5669d243e95ca7b437e3a167c170805ffd4aa8a9a786" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not win]

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake
    - ninja

test:
  commands:
    - if not exist %PREFIX%\\Library\\share\\cmake\\WIL\\wilConfig.cmake exit 1
    - if not exist %PREFIX%\\Library\\include\\wil\\com.h exit 1

about:
  home: https://github.com/microsoft/wil
  summary: Windows Implementation Libraries (WIL)
  description: >-
    The Windows Implementation Libraries (WIL) is a header-only C++ library created to make life easier for developers on Windows through readable type-safe C++ interfaces for common Windows coding patterns.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/Microsoft/wil/wiki
  dev_url: https://github.com/microsoft/wil

extra:
  recipe-maintainers:
    - teo-tsirpanis
    - jdblischak
    - Shelnutt2
